sync:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_KEY }}
      with:
        source-repo: 'git@github.com:HGthecode/thinkphp-apidoc.git'
        destination-repo: "git@gitee.com:hg-code/thinkphp-apidoc.git"

